export { ReactComponent as Cart } from './Cart.svg';
export { ReactComponent as Home } from './Home.svg';
export { ReactComponent as Person } from './Person.svg';
export { ReactComponent as Video } from './Video.svg';
export { ReactComponent as SearchIcon } from './Search.svg';
export { ReactComponent as LeftArrow } from './LeftArrow.svg';
export { ReactComponent as RightArrow } from './RightArrow.svg';
export { ReactComponent as UserCircle } from './UserCircle.svg';
export { ReactComponent as AddImage } from './AddImage.svg';
