export * from './DetailPage';
export * from './HomePage';
export * from './ListPage';
export * from './LivePage';
export * from './LoginPage';
export * from './MyPage';
export * from './RegisterPage';
export * from './FooterPage';
export * from './ProductPage';
