export const SKELETON_PRODUCT_DETAIL = {
  productId: 0,
  title: '',
  buyNowPrice: 0,
  auctionStartPrice: 0,
  auctionStartTime: '',
  auctionEndTime: '',
  productImages: ['/asset/김영진.jpg'],
  seller: 'Noelsky',
  like: false,
  live: false,
  description: '',
  sellReviewCount: 0,
  auctionReviewCount: 0,
  isAuction: true,
};
